# Generated by Django 4.0.4 on 2022-05-23 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidencetypes', '0001_initial'),
        ('means', '0001_initial'),
        ('unexpecteds', '0003_unexpected_color_u'),
        ('statuses', '0003_status_color_s'),
        ('thirds', '0003_third_contacto_third_correo_third_direccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_oc', models.DateTimeField(blank=True, null=True)),
                ('tittle', models.CharField(max_length=100)),
                ('oc_client', models.CharField(max_length=100)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('assign', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
                ('line', models.IntegerField(default=0)),
                ('rmv', models.IntegerField()),
                ('date_rmv', models.DateTimeField(blank=True, null=True)),
                ('incidencety', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidencetypes.incidencety')),
                ('mean', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='means.mean')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='statuses.status')),
                ('third', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='thirds.third')),
                ('unexpected', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unexpecteds.unexpected')),
            ],
        ),
    ]
