# Generated by Django 2.1.15 on 2022-07-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidences', '0002_incidence_line_r'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidence',
            name='observation',
            field=models.CharField(default='', max_length=500),
        ),
    ]
