# Generated by Django 2.1.15 on 2022-07-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle_s', models.CharField(max_length=100)),
                ('color_s', models.CharField(default='#fff', max_length=100)),
            ],
        ),
    ]
