# Generated by Django 4.0.4 on 2022-05-09 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='tittle',
            new_name='tittle_s',
        ),
    ]
