# Generated by Django 4.0.4 on 2022-05-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0002_rename_tittle_status_tittle_s'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='color_s',
            field=models.CharField(default='#fff', max_length=100),
        ),
    ]
