# Generated by Django 2.1.15 on 2022-07-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Third',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.IntegerField()),
                ('nombres', models.CharField(max_length=200)),
                ('contacto', models.CharField(default='', max_length=200)),
                ('correo', models.EmailField(default='', max_length=254, unique=True)),
                ('telefono', models.CharField(default='', max_length=50)),
                ('direccion', models.CharField(default='', max_length=500)),
                ('horario', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
