# Generated by Django 4.0.4 on 2022-05-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thirds', '0002_alter_third_nit'),
    ]

    operations = [
        migrations.AddField(
            model_name='third',
            name='contacto',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='third',
            name='correo',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='third',
            name='direccion',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='third',
            name='horario',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='third',
            name='telefono',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='third',
            name='nombres',
            field=models.CharField(max_length=200),
        ),
    ]
