# Generated by Django 4.0.4 on 2022-05-09 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unexpecteds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unexpected',
            old_name='tittle',
            new_name='tittle_u',
        ),
    ]
