# Generated by Django 4.0.4 on 2022-05-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unexpecteds', '0002_rename_tittle_unexpected_tittle_u'),
    ]

    operations = [
        migrations.AddField(
            model_name='unexpected',
            name='color_u',
            field=models.CharField(default='#fff', max_length=100),
        ),
    ]
