# Generated by Django 2.1.15 on 2022-07-06 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotetypes', '0001_initial'),
        ('unexpecteds', '0001_initial'),
        ('means', '0001_initial'),
        ('thirds', '0001_initial'),
        ('zones', '0001_initial'),
        ('statuses', '0001_initial'),
        ('incidencetypes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cot', models.DateTimeField(blank=True, null=True)),
                ('tittle_cot', models.CharField(max_length=100)),
                ('num_cot', models.IntegerField()),
                ('line', models.IntegerField(default=0)),
                ('assign', models.CharField(max_length=100)),
                ('recotization', models.BooleanField()),
                ('date_ppta', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('observation', models.CharField(max_length=500)),
                ('incidencety', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidencetypes.Incidencety')),
                ('mean', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='means.Mean')),
                ('quotety', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotetypes.Quotety')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='statuses.Status')),
                ('third', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='thirds.Third')),
                ('unexpected', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unexpecteds.Unexpected')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zones.Zone')),
            ],
        ),
    ]
