# Generated by Django 4.0.4 on 2022-05-26 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotetypes', '0001_initial'),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='incidencety2',
        ),
        migrations.AddField(
            model_name='quote',
            name='quotety',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotetypes.quotety'),
        ),
    ]
